### PR TITLE
Add LocalLogger class for logging to a local file

### PR DESCRIPTION
**Pull request by mattanapol**
This PR aiming to address issue [Save logs locally #288](https://github.com/lavague-ai/LaVague/issues/288)

By adding LocalLogger class that inherit AgentLogger

Usage:
- import LocalLogger module
```python
from lavague.core.logger import LocalLogger
```
- Create LocalLogger instance for web agent and world model
```python
    web_agent_local_logger = LocalLogger("web_agent_logs.json")
    world_model_local_logger = LocalLogger("world_agent_logs.json")
    driver = SeleniumDriver(headless=False)
    world_model = WorldModel()
    action_engine = ActionEngine(driver)
    agent = WebAgent(world_model, action_engine)
    agent.action_engine.set_logger_all(web_agent_local_logger)
    agent.world_model.set_logger(world_model_local_logger)
```

### CODE REVIEW

**Comment by lyie28** [comment]
Thanks - looks good. @JoFrost will review. Are you on our Discord server? Would be great to chat more with you there if you're interested in working on more issues with us :)

**Review by JoFrost — CHANGES_REQUESTED** [review]
Hey again @mattanapol, and thanks for that great PR! 
It looks good, but in my opinion, It would be better if the logger object could be passed to the WebAgent constructor. What do you think?

**Comment by mattanapol** [comment]
> Hey again @mattanapol, and thanks for that great PR! It looks good, but in my opinion, It would be better if the logger object could be passed to the WebAgent constructor. If nothing is specified, then we use the default logger. What do you think?

@JoFrost Sure, that would be the best way to do it.
Please review my latest change.

**Review by JoFrost — APPROVED** [review]

**Comment by JoFrost** [comment]
LGTM!

**Pull request merged**
