### PR TITLE
Add LiteLLM integration

### PR DESCRIPTION
**Pull request by isaac-chung**
Resolves https://github.com/lavague-ai/LaVague/issues/48

### CODE REVIEW

**Comment by isaac-chung** [comment]
The draft was to gauge if I'm in the right direction. Tested just now, and I had been getting an http error related to not calling `.read()` in streaming. The hurdle I have now is a 429 error from openAI (exceeded quota) for the API key.  

The error you shared above seems to be from llama-index, as neither LaVague nor LiteLLM implements `ChatMessage` afaik. What version of llama-index do you have?
```
(v1) Isaacs-MBP% pip list | grep llama-index
llama-index                              0.10.19
llama-index-agent-openai                 0.1.5
llama-index-cli                          0.1.9
llama-index-core                         0.10.19
llama-index-embeddings-azure-openai      0.1.5
llama-index-embeddings-huggingface       0.1.4
llama-index-embeddings-openai            0.1.6
llama-index-indices-managed-llama-cloud  0.1.4
llama-index-legacy                       0.9.48
llama-index-llms-azure-openai            0.1.5
llama-index-llms-huggingface             0.1.4
llama-index-llms-litellm                 0.1.3
llama-index-llms-openai                  0.1.9
llama-index-multi-modal-llms-openai      0.1.4
llama-index-program-openai               0.1.4
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.9
llama-index-readers-llama-parse          0.1.3
llama-index-retrievers-bm25              0.1.3
```

**Comment by dhuynh95** [comment]
Hi @isaac-chung!
Sorry for late reply, we have been quite busy.
I think we fixed llama-index to 0.10.19

Does the code work on your side? We have a [Docker image](https://docs.lavague.ai/en/latest/docs/get-started/setting-up-la-vague/#running-lavague-with-our-dev-container-docker-integration) into make things more reproducible.

Does your code work in this environment?

**Comment by isaac-chung** [comment]
Hey @dhuynh95 no worries. Thanks for the tip on using dev containers. I was able to reproduce the error seen by @lyie28 from above after installing  `llama-index-llms-litellm`. It came from [this line](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/base.py#L284) in llama-index, where the `"role"` key likely had a value of `None`, and there was no extra `or` statement at the end like there is on the next time. This is why role has a None value and failed the validation. 
```python
# litellm integration in llama-index
role = delta.get("role", "assistant")
content_delta = delta.get("content", "") or ""
```

The [OpenAI integration](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py#L458) does not have this issue because it does not have this bug:
```python
# openai integration in llama-index
role = delta.role or MessageRole.ASSISTANT
content_delta = delta.content or ""
```

So far I haven't found a workaround to inject role in a ChatMessage. I can open a separate PR in llama-index to fix the issue above though.

**Comment by isaac-chung** [comment]
With the new `llama-index-llms-litellm==0.1.4`, this code works in the dev container. I have also added an example notebook, as well as the dependency.
screencapture-1437d919bd4dec8648-gradio-live-2024-04-01-09_30_04

**Pull request merged**
